/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pc_monitor;

import picocli.CommandLine;

public class App {
    public static void main(String[] args) {
        int exitCode = new CommandLine(new Stats()).execute(args);
        System.exit(exitCode);
    }
}
