/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pc_monitor;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
      //  assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
